//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadre
    {
        public int idCadre { get; set; }
        public int idArticle { get; set; }
        public float DiametreVerre { get; set; }
        public Nullable<float> Pont { get; set; }
        public Nullable<float> LongeurBrache { get; set; }
        public Nullable<float> Largeur { get; set; }
        public Nullable<float> HauteurVerre { get; set; }
        public string Couleur { get; set; }
    
        public virtual article article { get; set; }
    }
}
