//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class examan
    {
        public int od_sphere_loins { get; set; }
        public int od_cylindre_loins { get; set; }
        public int od_axe_loins { get; set; }
        public int od_add_loins { get; set; }
        public int og_sphère_loins { get; set; }
        public int og_cylindre_loins { get; set; }
        public int og_axe_loins { get; set; }
        public int og_add_loins { get; set; }
        public int id { get; set; }
        public int visite_id { get; set; }
        public System.DateTime date_derniere_modif { get; set; }
        public string remarques { get; set; }
        public int og_add_pres { get; set; }
        public int od_sphere_pres { get; set; }
        public int od_cylindre_pres { get; set; }
        public int od_axe_pres { get; set; }
        public int od_add_pres { get; set; }
        public int og_sphère_pres { get; set; }
        public int og_cylindre_pres { get; set; }
        public int og_axe_pres { get; set; }
    
        public virtual visite visite { get; set; }
    }
}
