//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class examan
    {
        public int id { get; set; }
        public int visionLoins { get; set; }
        public int visionPres { get; set; }
        public string modifOrdonnance { get; set; }
        public string remarques { get; set; }
        public int visite_visiteId { get; set; }
        public int vision_loins_id { get; set; }
        public int vision_pres_id { get; set; }
    
        public virtual vision_loins vision_loins { get; set; }
        public virtual vision_pres vision_pres { get; set; }
        public virtual visite visite { get; set; }
    }
}
