//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class examan
    {
        public int od_sphere_loins { get; set; }
        public int od_cylindre_loins { get; set; }
        public int od_axe_loins { get; set; }
        public int od_add_loins { get; set; }
        public int og_sphère_loins { get; set; }
        public int og_cylindre_loins { get; set; }
        public int og_axe_loins { get; set; }
        public int og_add_loins { get; set; }
        public int id { get; set; }
        public int visite_id { get; set; }
        public System.DateTime date_derniere_modif { get; set; }
        public string remarques { get; set; }
        public int og_add_pres { get; set; }
        public int od_sphere_pres { get; set; }
        public int od_cylindre_pres { get; set; }
        public int od_axe_pres { get; set; }
        public int od_add_pres { get; set; }
        public int og_sphère_pres { get; set; }
        public int og_cylindre_pres { get; set; }
        public int og_axe_pres { get; set; }
    
        public virtual visite visite { get; set; }
    }
}
