//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lentille
    {
        public int idLentille { get; set; }
        public string idArticle { get; set; }
        public int idTypeLentille { get; set; }
        public Nullable<int> idOeil { get; set; }
        public string Couleur { get; set; }
    
        public virtual article article { get; set; }
        public virtual oeil oeil { get; set; }
        public virtual typelentille typelentille { get; set; }
    }
}
