//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class lentille
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lentille()
        {
            this.ligne_traitement_lentille = new HashSet<ligne_traitement_lentille>();
            this.visions = new HashSet<vision>();
        }
    
        public int idLentille { get; set; }
        public string idArticle { get; set; }
        public int idLigneType { get; set; }
        public string Couleur { get; set; }
        public int idtype_lentille { get; set; }
    
        public virtual article article { get; set; }
        public virtual type_lentille type_lentille { get; set; }
        public virtual ligne_type_lentille ligne_type_lentille { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_traitement_lentille> ligne_traitement_lentille { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vision> visions { get; set; }
    }
}
