//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_traitement_verre
    {
        public int idligne_traitement_verre { get; set; }
        public int verre_idVerre { get; set; }
        public int traitement_idTraitement { get; set; }
        public Nullable<int> niveau { get; set; }
    
        public virtual traitement traitement { get; set; }
        public virtual verre verre { get; set; }
    }
}
