//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_lentille_traitement
    {
        public Nullable<int> id_lentille { get; set; }
        public Nullable<int> id_traitement { get; set; }
        public int id { get; set; }
    
        public virtual lentille lentille { get; set; }
        public virtual traitement traitement { get; set; }
    }
}
