//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_traitement_verre
    {
        public int idligne_traitement_verre { get; set; }
        public int verre_idVerre { get; set; }
        public int traitement_idTraitement { get; set; }
        public Nullable<int> niveau { get; set; }
    
        public virtual traitement traitement { get; set; }
        public virtual verre verre { get; set; }
    }
}
