//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_traitement_lentille
    {
        public int idligne_traitement_lentille { get; set; }
        public int traitement_idTraitement { get; set; }
        public int lentille_idLentille { get; set; }
    
        public virtual lentille lentille { get; set; }
        public virtual traitement traitement { get; set; }
    }
}
