//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligneentree
    {
        public int idLigne { get; set; }
        public string idArticle { get; set; }
        public string idCmdClient { get; set; }
        public System.DateTime Date_Commande { get; set; }
        public string Adresse_Commande { get; set; }
        public int Qte_Commande { get; set; }
        public float Prix_Total { get; set; }
        public string EtatCmd { get; set; }
    
        public virtual article article { get; set; }
        public virtual cmdclient cmdclient { get; set; }
    }
}
