//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<cadre> cadres { get; set; }
        public virtual DbSet<categorie> categories { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<cmdclient> cmdclients { get; set; }
        public virtual DbSet<cmdfournisseur> cmdfournisseurs { get; set; }
        public virtual DbSet<fournisseur> fournisseurs { get; set; }
        public virtual DbSet<lentille> lentilles { get; set; }
        public virtual DbSet<ligne_traitement_verre> ligne_traitement_verre { get; set; }
        public virtual DbSet<lignecommande> lignecommandes { get; set; }
        public virtual DbSet<ligneentree> ligneentrees { get; set; }
        public virtual DbSet<ophtalmologue> ophtalmologues { get; set; }
        public virtual DbSet<ordonnance> ordonnances { get; set; }
        public virtual DbSet<reference> references { get; set; }
        public virtual DbSet<traitement> traitements { get; set; }
        public virtual DbSet<verre> verres { get; set; }
        public virtual DbSet<vision> visions { get; set; }
        public virtual DbSet<vision_detaille> vision_detaille { get; set; }
        public virtual DbSet<visite> visites { get; set; }
    }
}
