//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<cadre> cadres { get; set; }
        public virtual DbSet<categorie> categories { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<cmdclient> cmdclients { get; set; }
        public virtual DbSet<cmdfournisseur> cmdfournisseurs { get; set; }
        public virtual DbSet<examan> examen { get; set; }
        public virtual DbSet<fournisseur> fournisseurs { get; set; }
        public virtual DbSet<lentille> lentilles { get; set; }
        public virtual DbSet<lentillemultifocale> lentillemultifocales { get; set; }
        public virtual DbSet<lentillespherique> lentillespheriques { get; set; }
        public virtual DbSet<lentilletorique> lentilletoriques { get; set; }
        public virtual DbSet<lignecommande> lignecommandes { get; set; }
        public virtual DbSet<ligneentree> ligneentrees { get; set; }
        public virtual DbSet<oeil> oeils { get; set; }
        public virtual DbSet<ophtalmologue> ophtalmologues { get; set; }
        public virtual DbSet<ordonnance> ordonnances { get; set; }
        public virtual DbSet<traitement> traitements { get; set; }
        public virtual DbSet<typelentille> typelentilles { get; set; }
        public virtual DbSet<typeverre> typeverres { get; set; }
        public virtual DbSet<verre> verres { get; set; }
        public virtual DbSet<vision> visions { get; set; }
        public virtual DbSet<visite> visites { get; set; }
    }
}
