//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordonnance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordonnance()
        {
            this.visites = new HashSet<visite>();
        }
    
        public int id { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime dateExpiration { get; set; }
        public string notes { get; set; }
        public string photo { get; set; }
        public int ophtalmologueId { get; set; }
    
        public virtual ophtalmologue ophtalmologue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visite> visites { get; set; }
    }
}
