//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordonnance
    {
        public int id { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime dateExpiration { get; set; }
        public string typeVerres { get; set; }
        public string notes { get; set; }
        public string photo { get; set; }
        public int ophtalmologue_ophtalmologueId { get; set; }
        public string client_cin { get; set; }
        public int vision_pres_id { get; set; }
        public int vision_loins_id { get; set; }
    
        public virtual client client { get; set; }
        public virtual ophtalmologue ophtalmologue { get; set; }
        public virtual vision_loins vision_loins { get; set; }
        public virtual vision_pres vision_pres { get; set; }
    }
}
