//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class verre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public verre()
        {
            this.ligne_verre_traitement = new HashSet<ligne_verre_traitement>();
        }
    
        public int idVerre { get; set; }
        public int idArticle { get; set; }
        public int idTraitement { get; set; }
        public int idTypeVerre { get; set; }
        public int idOeil { get; set; }
        public string Modele { get; set; }
        public string Teinte { get; set; }
    
        public virtual article article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_verre_traitement> ligne_verre_traitement { get; set; }
        public virtual oeil oeil { get; set; }
        public virtual typeverre typeverre { get; set; }
    }
}
