//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vision_detaille
    {
        public int idvision_detaille { get; set; }
        public string remarques { get; set; }
        public int vision_id { get; set; }
        public int visite_id { get; set; }
    
        public virtual visite visite { get; set; }
    }
}
