//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vision
    {
        public int id { get; set; }
        public int od_sphere { get; set; }
        public int od_cylindre { get; set; }
        public int od_axe { get; set; }
        public int od_add { get; set; }
        public int og_sphère { get; set; }
        public int og_cylindre { get; set; }
        public int og_axe { get; set; }
        public int og_add { get; set; }
        public string vision_type { get; set; }
        public int ordonnance_id { get; set; }
    
        public virtual ordonnance ordonnance { get; set; }
    }
}
