//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vision
    {
        public int id { get; set; }
        public int od_sphere { get; set; }
        public int od_cylindre { get; set; }
        public int od_axe { get; set; }
        public int od_add { get; set; }
        public int og_sphère { get; set; }
        public int og_cylindre { get; set; }
        public int og_axe { get; set; }
        public int og_add { get; set; }
        public string vision_type { get; set; }
        public int ordonnance_id { get; set; }
    
        public virtual ordonnance ordonnance { get; set; }
    }
}
