//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vision_loins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vision_loins()
        {
            this.examen = new HashSet<examan>();
            this.ordonnances = new HashSet<ordonnance>();
        }
    
        public int id { get; set; }
        public int od_sphere { get; set; }
        public int od_cylindre { get; set; }
        public int od_axe { get; set; }
        public int od_add { get; set; }
        public int og_sphère { get; set; }
        public int og_cylindre { get; set; }
        public int og_axe { get; set; }
        public int og_add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examan> examen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordonnance> ordonnances { get; set; }
    }
}
