//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadre
    {
        public int idCadre { get; set; }
        public string idArticle { get; set; }
        public float DiametreVerre { get; set; }
        public Nullable<float> Pont { get; set; }
        public Nullable<float> LongeurBrache { get; set; }
        public Nullable<float> Largeur { get; set; }
        public Nullable<float> HauteurVerre { get; set; }
        public string Couleur { get; set; }
    
        public virtual article article { get; set; }
    }
}
