//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class examan
    {
        public int id { get; set; }
        public int visionLoins { get; set; }
        public int visionPres { get; set; }
        public string modifOrdonnance { get; set; }
        public string remarques { get; set; }
        public int visite_visiteId { get; set; }
        public int vision_loins_id { get; set; }
        public int vision_pres_id { get; set; }
    
        public virtual vision_loins vision_loins { get; set; }
        public virtual vision_pres vision_pres { get; set; }
        public virtual visite visite { get; set; }
    }
}
