//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class lentilletorique
    {
        public int idLentilleToriques { get; set; }
        public int idTypeLentille { get; set; }
        public Nullable<float> CYL { get; set; }
        public Nullable<float> AXE { get; set; }
    
        public virtual typelentille typelentille { get; set; }
    }
}
