//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class oeil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oeil()
        {
            this.lentilles = new HashSet<lentille>();
            this.verres = new HashSet<verre>();
        }
    
        public int idOeil { get; set; }
        public float SPH_G { get; set; }
        public float CYL_G { get; set; }
        public float AXE_G { get; set; }
        public float ADD_G { get; set; }
        public float SPH_D { get; set; }
        public float CYL_D { get; set; }
        public float AXE_D { get; set; }
        public float ADD_D { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lentille> lentilles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<verre> verres { get; set; }
    }
}
