//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuWithSubMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class verre
    {
        public int idVerre { get; set; }
        public string idArticle { get; set; }
        public int idTraitement { get; set; }
        public int idTypeVerre { get; set; }
        public int idOeil { get; set; }
        public string Modele { get; set; }
        public string Teinte { get; set; }
    
        public virtual article article { get; set; }
        public virtual oeil oeil { get; set; }
        public virtual traitement traitement { get; set; }
        public virtual typeverre typeverre { get; set; }
    }
}
