using MenuWithSubMenu.Model;
using MenuWithSubMenu.Utils;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace MenuWithSubMenu.Pages
{
    /// <summary>
    /// Interaction logic for Outbox.xaml
    /// </summary>
    public partial class EspaceStock : Page
    {
        dbEntities db;
        List<article> listArticle;
        int count;

        public EspaceStock()
        {

            InitializeComponent();

            db = new dbEntities();
            searchBar.Text = "";
            getArticles(0);
        }

        private async void getArticles(int skip)
        {
            loadingBox.Visibility = Visibility.Visible;
            articlesDataGrid.Visibility = Visibility.Hidden;

            try
            {
                listArticle = searchBar.Text != "" ? await db.articles.Where(c => c.Designation.Contains(searchBar.Text)).ToListAsync() : await db.articles.ToListAsync();

                count = (int)Math.Ceiling((decimal)listArticle.Count / 10);
                pagination.MaxPageCount = count;
                articlesDataGrid.ItemsSource = listArticle.Skip(skip).Take(10);

            }
            catch (Exception exp)
            {
                Console.WriteLine(exp.Message);
            }
            finally
            {
                loadingBox.Visibility = Visibility.Hidden;
                articlesDataGrid.Visibility = Visibility.Visible;
            }
        }


        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "Edit")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        private void AddPresetButton_Click(object sender, RoutedEventArgs e)
        {
            var addButton = sender as FrameworkElement;
            if (addButton != null)
            {
                addButton.ContextMenu.IsOpen = true;
            }
        }

        private void voirArticle(object sender, RoutedEventArgs e)
        {
            article articleRow = articlesDataGrid.SelectedItem as article;
            int articleId = articleRow.idArticle;

            ArticleAbout articleAbout = new ArticleAbout(articleId, this);


            MyContext.navigateTo(articleAbout);
        }

        private void updateArticle(object sender, RoutedEventArgs e)
        {

            article articleRow = articlesDataGrid.SelectedItem as article;
            int articleId = articleRow.idArticle;
            UpdateArticle update = new UpdateArticle(db.articles.Where(article => article.idArticle == articleId).SingleOrDefault(), this);
            MyContext.navigateTo(update);
        }
        private void deleteArticle(object sender, RoutedEventArgs e)
        {

            /*try
            {
                DbContextTransaction transaction = db.Database.BeginTransaction();
                article articleRow = articlesDataGrid.SelectedItem as article;

                db.ordonnances.RemoveRange(db.ordonnances.Where(r => r.article_cin == articleRow.cin));
                db.SaveChanges();

                db.visites.RemoveRange(db.visites.Where(r => r.article_cin == articleRow.cin));
                db.SaveChanges();

                db.articles.Remove(articleRow);
                db.SaveChanges();

                transaction.Commit();

                System.Windows.MessageBox.Show("Success");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }*/


        }
        private void addArticle(object sender, RoutedEventArgs e)
        {
            AddArticle add_article = new AddArticle(this);
            MyContext.navigateTo(add_article);
        }

        private void page_PageUpdated(object sender, HandyControl.Data.FunctionEventArgs<int> e)
        {

            getArticles((e.Info - 1) * 10);
        }

        private void SearchBar_TextChanged(object sender, TextChangedEventArgs e)
        {
            getArticles(0);

        }

        private void CancelFocus_Click(object sender, RoutedEventArgs e)
        {
            searchBar.Text = "";
        }
    }
}
