using MenuWithSubMenu.Model;
using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace MenuWithSubMenu.Pages
{
    /// <summary>
    /// Interaction logic for Dashboard.xaml
    /// </summary>
    public partial class Dashboard : Page
    {
        public Dashboard()
        {
            InitializeComponent();

            // show loading


            dbEntities db = new dbEntities();
            try
            {
                visitesDataGrid.ItemsSource = db.visites.ToList();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            finally
            {
                // hide loading
            }
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            foreach (var item in grid.Columns)
            {
                if (item.Header.ToString() == "")
                {
                    item.DisplayIndex = grid.Columns.Count - 1;
                    break;
                }
            }
        }

        private void AddPresetButton_Click(object sender, RoutedEventArgs e)
        {
            var addButton = sender as FrameworkElement;
            if (addButton != null)
            {
                addButton.ContextMenu.IsOpen = true;
            }
        }

        private void voirClient(object sender, RoutedEventArgs e)
        {
            visite visiteRow = visitesDataGrid.SelectedItem as visite;
            string clientCin = visiteRow.client_cin;

            
            foreach (System.Windows.Window window in Application.Current.Windows)
            {
                if (window.GetType() == typeof(MainWindow))
                {
                    ClientProfile clientProfile = new ClientProfile(clientCin);
                    (window as MainWindow).MainWindowFrame.Navigate(clientProfile);
                }
            }
        }
    }
}
